### ISSUE TITLE
Please help me, how to convert a.txt file to a usable.h5 file

### ISSUE THREAD

**Issue by caijiqzj** [LiuZH-19/ESG#1]
Hi, I want to run this network with my own data set, but my file is a txt file like solar-energy, which is used to do multivariate time series prediction

**Comment by DavidDong004** [comment]
Hi，didi you save the problem？I meet the same problem with you，thanks。

**Comment by LiuZH-19** [comment]
Here is an article about [Using HDF5 with Python](https://medium.com/@jerilkuriakose/using-hdf5-with-python-6c5242d08773).

**Comment by caijiqzj** [comment]
> Here is an article about [Using HDF5 with Python](https://medium.com/@jerilkuriakose/using-hdf5-with-python-6c5242d08773).

Thanks for your reply, I have rewritten dataLoda and it can run now

**Comment by caijiqzj** [comment]
> Hi，didi you save the problem？I meet the same problem with you，thanks。

I've rewritten dataLoda to run like mtgnn

**Comment by YoungXiee** [comment]
> > Hi，didi you save the problem？I meet the same problem with you，thanks。
> 
> I've rewritten dataLoda to run like mtgnn

hi,i have meet the same problem,can you share how to rewrite the dataloader? Thank you

**Comment by DavidDong004** [comment]
> > Hi，didi you save the problem？I meet the same problem with you，thanks。
> 
> I've rewritten dataLoda to run like mtgnn

Thanks，I will try it.

**Comment by alwaysliyuan** [comment]
`import pandas as pd

# 读取文本文件到DataFrame
txt_file_path = 'machine-1-1.txt'
df = pd.read_csv(txt_file_path, sep=',', header=None)  # 假设文本文件没有列名

# 将DataFrame保存为HDF5文件
h5_file_path = 'machine-1-1.h5'
df.to_hdf(h5_file_path, key='data', mode='w')

print(f'数据已成功保存到 {h5_file_path}')
`
这样格式的可以生成的h5,可以允许

**Comment by alwaysliyuan** [comment]
import pandas as pd

txt_file_path = 'machine-1-1.txt'
df = pd.read_csv(txt_file_path, sep=',', header=None) 

h5_file_path = 'machine-1-1.h5'
df.to_hdf(h5_file_path, key='data', mode='w')
